# Generated by Django 5.0 on 2023-12-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='property',
            new_name='priority',
        ),
    ]
